const now = Date.now();

export const sampleLeads = [
  {
    id: 'lead_demo_1',
    conversationId: 'conv_demo_1',
    createdAt: new Date(now - 1000 * 60 * 60 * 26).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 34).toISOString(),
    source: 'landing_hero',
    name: 'Marco',
    email: 'marco@deskmail.io',
    stage: 'qualified',
    segment: 'advanced',
    leadScore: 82,
    intentLevel: 'hot',
    recommendedNextAction: 'book_demo',
    profile: {
      marketPreference: 'futures',
      assets: ['SOLUSDT', 'ETHUSDT'],
      tradingFrequency: 'daily',
      currentTools: ['TradingView', 'manual screening'],
      struggles: ['late entries', 'too much noise'],
      desiredOutcome: ['early detection', 'structure confirmation'],
    },
    objections: ['I already use TradingView'],
    ctaHistory: [{ type: 'book_demo', label: 'Book Demo', timestamp: new Date(now - 1000 * 60 * 40).toISOString() }],
    conversation: [
      {
        role: 'assistant',
        content: "I’m AMAIA Sales AI. I’ll help you determine if this platform gives you a real edge.",
        timestamp: new Date(now - 1000 * 60 * 60 * 26).toISOString(),
      },
      {
        role: 'user',
        content: 'I trade futures daily and I am tired of seeing the move after everyone else.',
        timestamp: new Date(now - 1000 * 60 * 60 * 25).toISOString(),
      },
    ],
    escalation: null,
  },
  {
    id: 'lead_demo_2',
    conversationId: 'conv_demo_2',
    createdAt: new Date(now - 1000 * 60 * 60 * 9).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 20).toISOString(),
    source: 'pricing_card',
    name: 'Sara',
    email: 'sara@alphaflow.co',
    stage: 'nurturing',
    segment: 'retail',
    leadScore: 46,
    intentLevel: 'warm',
    recommendedNextAction: 'start_trial',
    profile: {
      marketPreference: 'spot',
      assets: ['AI tokens', 'small caps'],
      tradingFrequency: 'weekly',
      currentTools: ['exchange watchlists'],
      struggles: ['manual scanning takes too long'],
      desiredOutcome: ['alerts', 'early detection'],
    },
    objections: ['Why should I pay?'],
    ctaHistory: [],
    conversation: [],
    escalation: null,
  },
];
